Homeless people in essence

In [ ]:
import pandas as pd

df = pd.read_parquet('elections.parquet')
df

,azganun,anun,haeranun,or_amis_tari,marz,hamaenq,bnakavaer,hasce,taracq,texamas
0,Հարությունյան,Կարեն,Շաքարի,14/11/1997,ԿՈՏԱՅՔ,ՆՈՐ ՀԱՃՆ,None,Չարենցի Փ. 31 1,28,28/01
1,Աղաջանյան,Կարինե,Ժորայի,14/08/1964,ԿՈՏԱՅՔ,ՆՈՐ ՀԱՃՆ,None,Չարենցի Փ. 31 1,28,28/01
2,Հարությունյան,Հարություն,Շաքարի,29/10/1986,ԿՈՏԱՅՔ,ՆՈՐ ՀԱՃՆ,None,Չարենցի Փ. 31 1,28,28/01
3,Ալեքսանյան,Համեստ,Արսենի,24/10/1954,ԿՈՏԱՅՔ,ՆՈՐ ՀԱՃՆ,None,Չարենցի Փ. 26 71,28,28/01
4,Հարությունյան,Շաքար,Արտաշի,01/01/1959,ԿՈՏԱՅՔ,ՆՈՐ ՀԱՃՆ,None,Չարենցի Փ. 31 1,28,28/01
...,...,...,...,...,...,...,...,...,...,...
2577168,Շահվերդյան,Ալա,Աղասու,22/04/1987,ԼՈՌԻ,ՎԱՆԱՁՈՐ,None,1 Փ. 5 Փկղ. 8,23,23/58
2577169,Իսրաելյան,Կարինե,Վահանի,13/03/1960,ԼՈՌԻ,ԴԵԲԵԴ,None,6 Փ. 5,23,23/58
2577170,Գրիգորյան,Անահիտ,Հունանի,12/05/1970,ԼՈՌԻ,ՎԱՆԱՁՈՐ,None,Արճիս 5 Փ. 7 1,23,23/58
2577171,Սահակյան,Նարինե,Աշոտի,25/09/1978,ԼՈՌԻ,ՎԱՆԱՁՈՐ,None,Կ. Դեմիրճյան Փ. 26 22,23,23/58
2577172,Մկրտչյան,Գայանե,Գարուշի,24/04/1966,ԼՈՌԻ,ՎԱՆԱՁՈՐ,None,Տարոն 3 Քշհ 7 48 7,23,23/58

In [3]:
df[df['hasce'].isna()]

,azganun,anun,haeranun,or_amis_tari,marz,hamaenq,bnakavaer,hasce,taracq,texamas
45851,Արամյան,Նելլի,Դերենիկի,12/08/1988,ԿՈՏԱՅՔ,ԲՅՈՒՐԵՂԱՎԱՆ,None,None,28,28/07
46024,Հարությունյան,Ծաղիկ,Լեւիկի,01/03/1960,ԿՈՏԱՅՔ,ՄՐԳԱՇԵՆ,None,None,28,28/29
46025,Հարությունյան,Հայկ,Ռուբիկի,31/05/1958,ԿՈՏԱՅՔ,ՄՐԳԱՇԵՆ,None,None,28,28/29
46039,Աղասյան,Սերյոժա,Աշոտի,16/10/1995,ԿՈՏԱՅՔ,ՆՈՐ ԳԵՂԻ,None,None,28,28/31
46154,Համբարյան,Մովսես,Թադեւոսի,23/11/1975,ԼՈՌԻ,ԽՆԿՈՅԱՆ,None,None,22,22/01
...,...,...,...,...,...,...,...,...,...,...
2483108,Նալբանդյան,Ավետ,Վարդանի,27/04/1994,ԵՐԵՎԱՆ,ԿԵՆՏՐՈՆ,None,None,9,9/34
2483318,Ափոյան,Վահան,Վիկտորի,20/06/1963,ԳԵՂԱՐՔՈՒՆԻՔ,ԲԱՐԵՊԱՏ,None,None,9,9/45
2483328,Գյուրջյան,Դավիթ,Գեորգիի,18/03/1991,ԵՐԵՎԱՆ,ԿԵՆՏՐՈՆ,None,None,9,9/46
2483482,Սիրադեղյան,Սյուզաննա,Սեյրանի,05/05/1988,ԵՐԵՎԱՆ,ԿԵՆՏՐՈՆ,None,None,9,9/53
2576806,Թամազյան,Նարինե,Հովիկի,11/08/1990,ԼՈՌԻ,ՎԱՆԱՁՈՐ,None,None,23,23/20